### ISSUE TITLE
Y u no build shared?

### ISSUE THREAD

**Issue by nephros** [rinigus/pkg-libmicrohttpd#1]
Any reason why this builds a static library only?

Would a PR enabling building a shared library in addition (or instead) be accepted?

**Comment by rinigus** [comment]
It is built as static to simplify linking to it by OSM Scout Server. That is from the days I had the server in the official store and had to bundle all the libs. If you wish to have it dynamically built and have a use case for it, sure we can do that. If it is possible to build the both versions, that would be nice as well.

Note that OBS will be rebuilding all packages depending on the shared lib (bit of stupidity from OBS). So, if we will bump libmicrohttpd, all other packages will be rebuilt as well. And users will end up updating them all anyway. In this respect, static lib is as good as dynamic in this sense. Except, obviously, having the same code linked into executables multiple times in the system.

I hope I replied to "Why". As for "whether it will be accepted" -> yes, it will. Just think through if you need and want it. I'll be fine with making changes to the server if needed.

**Comment by nephros** [comment]
Thanks for the thorough answer.

Good point about the current dependants. As currently I have one small package which only needs it as an *optional* depencency, there is no dire need for a change.

Building and packaging both is possible, see e.g. https://build.sailfishos.org/package/view_file/home:nephros:devel:musikcube/libmicrohttpd/libmicrohttpd.spec?expand=1 which has a -devel and a -static package.

Closing for now.
